/twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel_nav
        timeout : 0.1
        priority: 10
      joypad:
        topic   : /cmd_vel_joypad
        timeout : 0.01
        priority: 100
      keyobard:
        topic   : /cmd_vel_key
        timeout : 0.01
        priority: 100
    